export const tweets = [
  {
    id: 1,
    author: 'Frke Doe',
    handle: '@frkedoe',
    avatar: 'https://pbs.twimg.com/profile_images/1284868602391220224/1YYk51bx_400x400.jpg',
    content:
      "HourBlock is a game-changer! My productivity has gone through the roof. I used to struggle with time management, but now I'm accomplishing more than ever. The intuitive interface and smart features have revolutionized my workday. Highly recommend to anyone looking to boost their efficiency! 🚀",
    date: '2h ago',
  },
  {
    id: 2,
    author: 'Jane Smith',
    handle: '@janesmith',
    avatar: 'https://pbs.twimg.com/profile_images/1821765131497316352/EsxfxXNG_400x400.jpg',
    content:
      "I've tried a bunch of time management apps, but HourBlock is the real deal. It's so intuitive! The way it seamlessly integrates with my workflow is impressive. I've seen a significant improvement in my task completion rate, and my stress levels have dropped considerably. It's like having a personal productivity coach right on my device.",
    date: '5h ago',
  },
  {
    id: 3,
    author: 'Mike Johnson',
    handle: '@mikej',
    avatar: 'https://pbs.twimg.com/profile_images/855044616881614848/6IaSCaSf_400x400.jpg',
    content:
      "HB's customization is 👌. Fits my workflow like a glove! The ability to tailor every aspect to my needs has made it an indispensable tool in my daily routine. From custom tags to personalized notifications, it's like the app was built just for me.",
    date: '1d ago',
  },
  {
    id: 4,
    author: 'Emily Brown',
    handle: '@emilybrown',
    avatar: 'https://pbs.twimg.com/profile_images/1633201201247567872/4lvCylo4_400x400.jpg',
    content: 'HourBlock + my calendar = match made in heaven! Time management on steroids. 💪',
    date: '3d ago',
  },
  {
    id: 5,
    author: 'Alex Lee',
    handle: '@alexlee',
    avatar: 'https://pbs.twimg.com/profile_images/1614839340995346432/LNXlBNUo_400x400.jpg',
    content:
      "Our team's crushing it with Hour Block's collab features. Productivity to the moon! 🌙",
    date: '1w ago',
  },
  {
    id: 6,
    author: 'Sarah Wilson',
    handle: '@sarahw',
    avatar: 'https://pbs.twimg.com/profile_images/1474329851850985475/zuqzjvwX_400x400.jpg',
    content: "Even my tech-phobic dad loves HourBlock. It's THAT user-friendly!",
    date: '2w ago',
  },
  {
    id: 7,
    author: 'David Chen',
    handle: '@davidc',
    avatar: 'https://pbs.twimg.com/profile_images/1777849053390467072/ioKIzkbP_400x400.jpg',
    content: 'HourBlock mobile app = productivity on-the-go. No excuses now! 😅',
    date: '3w ago',
  },
  {
    id: 8,
    author: 'Yuki Tanaka',
    handle: '@yukitanaka',
    avatar: 'https://pbs.twimg.com/profile_images/1691777625897787392/oFrTrfPE_400x400.jpg',
    content: 'HourBlockの日本語版最高！使いやすさ100点満点です👍',
    date: '4h ago',
  },
  {
    id: 9,
    author: 'Emirer',
    handle: '@Emirer431__',
    avatar: 'https://pbs.twimg.com/profile_images/1817463415306117120/LMOdZQwJ_400x400.jpg',
    content: 'HBで時間管理がラクラク。これぞ働き方改革の味方だね！',
    date: '1d ago',
  },
  {
    id: 10,
    author: 'Lisa Johnson',
    handle: '@lisaj',
    avatar: 'https://pbs.twimg.com/profile_images/1609897289396682753/TyBhJRKu_400x400.jpg',
    content: 'Mind = blown 🤯 HourBlock just changed my entire day!',
    date: '30m ago',
  },
  {
    id: 11,
    author: 'Hiroshi Yamamoto',
    handle: '@hiroshiy',
    avatar: 'https://pbs.twimg.com/profile_images/1612350794451554304/SndROM0e_400x400.jpg',
    content: 'Hour Blockで生産性アップ！日本中の会社に広まってほしいな。',
    date: '5d ago',
  },
  {
    id: 12,
    author: 'Emma Watson',
    handle: '@emmaw',
    avatar: 'https://pbs.twimg.com/profile_images/1715972986774368256/pAvfKKQz_400x400.jpg',
    content: "Crazy schedule? HourBlock to the rescue! Can't recommend it enough. 🦸‍♀️",
    date: '2h ago',
  },
  {
    id: 13,
    author: 'Takeshi Kato',
    handle: '@takeshik',
    avatar: 'https://pbs.twimg.com/profile_images/1782842633208946689/zsFs2GEK_400x400.jpg',
    content: 'HBは日本の働き方にピッタリ。カスタマイズ性が高くて助かります！',
    date: '1w ago',
  },
  {
    id: 14,
    author: 'Sophie Martin',
    handle: '@sophiem',
    avatar: 'https://pbs.twimg.com/profile_images/1801615295104356355/pdbguwSs_400x400.jpg',
    content: 'HourBlock obsessed! My days have never been this organized. 😍',
    date: '15m ago',
  },
  {
    id: 15,
    author: 'Akira Tanaka',
    handle: '@akirat',
    avatar: 'https://pbs.twimg.com/profile_images/1635175648280080389/BTA_ydCE_400x400.jpg',
    content: 'Hour Blockで言語の壁を超えた！国際チームとの連携が超スムーズに。',
    date: '3d ago',
  },
  {
    id: 16,
    author: '李明',
    handle: '@liming',
    avatar: 'https://pbs.twimg.com/profile_images/1613342972543926272/OB7WGezU_400x400.jpg',
    content: 'HourBlock真是太棒了！效率飞升，工作生活两不误！👍',
    date: '1h ago',
  },
  {
    id: 17,
    author: '王芳',
    handle: '@wangfang',
    avatar: 'https://pbs.twimg.com/profile_images/1744269660395061249/4xMLYNHR_400x400.jpg',
    content: 'HourBlock中文界面好友好，用起来超顺手。工作安排从未如此轻松！',
    date: '4h ago',
  },
  {
    id: 18,
    author: '张伟',
    handle: '@zhangwei',
    avatar: 'https://cdn-icons-png.flaticon.com/512/3135/3135823.png',
    content: '身为项目经理，有了HourBlock简直如虎添翼。团队效率蹭蹭往上涨！',
    date: '2d ago',
  },
];
